# Generated by Django 3.1.5 on 2021-02-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society_reg', '0004_auto_20210222_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistor',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='society_reg.society'),
        ),
    ]
