# Generated by Django 3.1.5 on 2021-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_reg', '0006_auto_20210222_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistor',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
