# Generated by Django 3.1.5 on 2021-02-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_reg', '0007_auto_20210222_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vistor',
            new_name='Visitor',
        ),
    ]
